### ISSUE TITLE
Does not  support Samsung G9000F 

### ISSUE THREAD

**Issue by Makova** [JustArchi/ArchiKitchen#31]
Hey Archi. 
Do you know If the kitchen works on Samsung S5?. Because it flashes but does not turn on.
I cooked the ROM G900FXXU1BNL9 with your Kitchen.
Thanks!
![ladejoya](https://cloud.githubusercontent.com/assets/3070918/5598178/52e514ac-92b1-11e4-9c2c-9480270d3f39.png)

**Comment by JustArchi** [comment]
Hey.

AK is just a tool that blindly executes some scripted actions, it has no idea if the final effect is flashable or works.

I don't own your device and I don't know what can be wrong. You can try making pure bare stock ROM with knox and bloat, just to see if it boots.

Other tip could be verifying that permissions are OK. Symlinks should be, as they're generated from the image, but permissions are not.

If you find out what's wrong, let me know.

Good luck.

**Comment by JustArchi** [comment]
Symlinks/Permissions should be proper with latest https://github.com/JustArchi/ArchiKitchen/commit/d13663769bd40d1e9d89672fd8749fdb327c4dda commit.

For some reason your recovery may not mount /system automatically, so just mount it manually before flashing.

**Comment by JustArchi** [comment]
No response in a week, considering fixed.
