### ISSUE TITLE
Add Support for Installation with TWRP if possible

### ISSUE THREAD

**Issue by kostoulhs** [JustArchi/ArchiKitchen#32]
When flashing with TWRP, this message appears: Can't execute update binary.

**Comment by JustArchi** [comment]
Because you should put your device's update-binary, my universal one won't work for every device.

**Comment by JustArchi** [comment]
Which device?

**Comment by kostoulhs** [comment]
Ace 3 lte, it is strange, because it works with CWM 6.0.5.1, but not with TWRP 2.8.1.0

**Comment by JustArchi** [comment]
Possible that your TWRP is not working properly if it works with CWM.

**Comment by JustArchi** [comment]
Or just put your device's update binary. This is not AK's issue.

**Comment by kostoulhs** [comment]
Sir, something else. TWRP can Install CM11 and CM12. If I replace AK update_binary with the one from CM11 will it work?

**Comment by JustArchi** [comment]
Why you won't try?
