### ISSUE TITLE
building also adds the bloatware folder for some reason

### ISSUE THREAD

**Issue by eladkarako** [JustArchi/ArchiKitchen#50]
<img src="https://i.imgur.com/Gt5qLzt.gif"/>

also it adds an empty folder that ends with a dot,
maybe it is a type and the folder should have started with a dot (hidden) so it won't get into the zip and for some reason the dot was dropped?

<img src="https://i.imgur.com/L8BT4PR.gif"/>

I was moved those two folders out (up..) temporary while building.

**Comment by JustArchi** [comment]
Sorry but AK is EOL and unsupported since several years now, I don't recommend using it anymore, there are probably better and more updated alternatives.
